language: node_js
node_js: stable

# S: Build Lifecycle
# install:
#   - npm install


#before_script:
 # - npm install -g gulp

before_install:
 - export CHROME_BIN=chromium-browser
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start

# script:
#   - hexo g

after_script:
  - cd ./src
  - git init
  - git config user.name "kylin"
  - git config user.email "396882574@qq.com"
  - git add .
  - git commit -m "TravisCI"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages
# E: Build LifeCycle

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/Himmas/melody.git
